### ISSUE TITLE
Set up Rails within the VM

### ISSUE THREAD

**Issue by GRardB** [BlackathonBlackers/minority-stories#2]
Creating a bash script to do this for us would be really handy. If not, putting instructions in the README will suffice for now.

**Comment by iheanyi** [comment]
Hmmmm,  shouldn't a simple gem install handle this?

**Comment by GRardB** [comment]
You tell me, bruh. I know nothing, lmao.

**Comment by GRardB** [comment]
I'm dumb and `bundle install` will suffice.
